crayon:
  restart: always
  image: nginx:1.13.1
  ports:
    - "1234:80"
  volumes:
    - ./source:/data/source
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./log/:/data/log/
  links:
    - php
php:
  image: php:7.1.5-fpm-alpine
  volumes:
    - ./source:/data/source
    - ./php.ini:/usr/local/etc/php/php.ini

